--Add a bunch of mock item data to work with
INSERT INTO Items (name,description,price,type,secret_field) VALUES ('Samsung 55 TV','Samsung 55 LCD HD TV',1500.0,'Electronics', 'super secret');
INSERT INTO Items (name,description,price,type,secret_field) VALUES ('Sony 55 TV','Sony Bravia 55 LCD HD TV',1350.0,'Electronics', 'super secret');
INSERT INTO Items (name,description,price,type,secret_field) VALUES ('Vizio 70 TV','Vizio 70 LCD HD TV',3500.0,'Electronics', 'super secret');
INSERT INTO Items (name,description,price,type,secret_field) VALUES ('LG 48 TV','LG 48 LCD UHD TV',500.0,'Electronics', 'super secret');
INSERT INTO Items (name,description,price,type,secret_field) VALUES ('Playstation 4','Sony entertainment console',399.99,'Electronics', 'super secret');
INSERT INTO Items (name,description,price,type,secret_field) VALUES ('Xbox One','Microsoft entertainment console',399.99,'Electronics', 'super secret');
INSERT INTO Items (name,description,price,type,secret_field) VALUES ('Dell Computer','Dell computer',1000.0,'Electronics', 'super secret');
INSERT INTO Items (name,description,price,type,secret_field) VALUES ('Apple MacBook Pro','Apple Professional Laptop',2000.0,'Electronics', 'super secret');
INSERT INTO Items (name,description,price,type,secret_field) VALUES ('Sony 78 TV','Sony Bravia 78 LCD UHD TV',5000.0,'Electronics', 'super secret');
INSERT INTO Items (name,description,price,type,secret_field) VALUES ('Ready Player One','Book full of 80s references',11.99,'Books', 'super secret');
INSERT INTO Items (name,description,price,type,secret_field) VALUES ('The Martian','Matt Damon lost is space again',24.99,'Movies', 'super secret');
INSERT INTO Items (name,description,price,type,secret_field) VALUES ('Animal Farm','Allegory about Stalinism',9.99,'Books', 'super secret');
INSERT INTO Items (name,description,price,type,secret_field) VALUES ('World War Z','Post-zombie apocalypse war book',14.99,'Books', 'super secret');
INSERT INTO Items (name,description,price,type,secret_field) VALUES ('World War Z','A movie in no way based upon the book of the same name',24.99,'Movies', 'super secret');
INSERT INTO Items (name,description,price,type,secret_field) VALUES ('Effective Java','An essential book for all Java developers',19.99,'Books', 'super secret');
INSERT INTO Items (name,description,price,type,secret_field) VALUES ('Civilization V','One more turn...',20.0,'Games', 'super secret');
INSERT INTO Items (name,description,price,type,secret_field) VALUES ('Factorio','Factory game',10.0,'Electronics', 'super secret');
INSERT INTO Items (name,description,price,type,secret_field) VALUES ('Sony Digital Camera','Just use the camera in your phone',100.0,'Electronics', 'super secret');
INSERT INTO Items (name,description,price,type,secret_field) VALUES ('Domain Driven Design','An essential book for all seasoned developers',34.99,'Books', 'super secret');
INSERT INTO Items (name,description,price,type,secret_field) VALUES ('Guardians of the Galaxy','Chris Pratt sooo hot right now',20.0,'Movies', 'super secret');
INSERT INTO Items (name,description,price,type,secret_field) VALUES ('Independence Day','Best. Movie. Speech. Ever!',10.0,'Movies', 'super secret');
INSERT INTO Items (name,description,price,type,secret_field) VALUES ('Robocop','When hard R movies were marketed to kids',10.0,'Movies', 'super secret');
INSERT INTO Items (name,description,price,type,secret_field) VALUES ('The Fifth Element','Multipass!',10.0,'Movies', 'super secret');